Improve build.sbt

diff --git a/.github/workflows/docker-ci.yaml b/.github/workflows/docker-ci.yaml
--- a/.github/workflows/docker-ci.yaml
+++ b/.github/workflows/docker-ci.yaml
@@ -1,25 +1,70 @@
 name: Docker CI
-
 on:
   pull_request:
     paths:
       - .github/workflows/docker-ci.yaml
+      - .github/scripts/**
       - build.sbt
+      - src/**
+
+env:
+  GITHUB_TOKEN: ${{ secrets.READ_PACKAGES }}
 
 jobs:
-  docker-build:
-    runs-on: ubuntu-latest
+  build-and-test:
+    name: Build & Test
+    runs-on: self-hosted
     steps:
       - uses: actions/checkout@v4
-      - uses: docker/setup-buildx-action@v3
-      - uses: actions/setup-java@v4
-        with:
-          distribution: 'temurin'
-          java-version: '21'
-      - uses: sbt/setup-sbt@v1
-        with:
-          sbt-runner-version: 1.9.9
+
       - name: Build Docker image
-        env:
-          GITHUB_TOKEN: ${{ secrets.READ_PACKAGES }}
-        run: sbt docker/Docker/publishLocal
+        run: |
+          .github/scripts/dnd-sbt Docker/publishLocal
+          IMAGE_NAME=$(.github/scripts/dnd-sbt printDockerImageName | grep DOCKER_IMAGE | cut -d= -f2)
+          echo "IMAGE=${IMAGE_NAME}" >> $GITHUB_ENV
+
+      - name: Test image - run container
+        run: |
+          CONTAINER_ID=$(docker run -d -p 50051 ${IMAGE})
+          echo "CONTAINER_ID=${CONTAINER_ID}" >> $GITHUB_ENV
+          HOST_PORT=$(docker port ${CONTAINER_ID} 50051 | cut -d':' -f2)
+          echo "HOST_PORT=${HOST_PORT}" >> $GITHUB_ENV
+          sleep 15
+
+      - name: Test image - verify service is running
+        run: |
+          nc -z localhost ${HOST_PORT}
+          if [ $? -ne 0 ]; then
+            echo "Service check failed!"
+            exit 1
+          fi
+
+      - name: Cleanup container
+        if: always()
+        run: |
+          if [ ! -z "${CONTAINER_ID}" ]; then
+            docker stop ${CONTAINER_ID}
+            docker rm ${CONTAINER_ID}
+          fi
+
+  security-scan:
+    name: Security Scan
+    runs-on: self-hosted
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Build Docker image
+        run: |
+          .github/scripts/dnd-sbt Docker/publishLocal
+          IMAGE_NAME=$(.github/scripts/dnd-sbt printDockerImageName | grep DOCKER_IMAGE | cut -d= -f2)
+          echo "IMAGE=${IMAGE_NAME}" >> $GITHUB_ENV
+
+      - name: Run Trivy vulnerability scanner
+        uses: aquasecurity/trivy-action@master
+        with:
+          image-ref: ${{ env.IMAGE }}
+          format: 'table'
+          exit-code: '1'
+          ignore-unfixed: true
+          vuln-type: 'os,library'
+          severity: 'CRITICAL,HIGH'
